title: 3Z6MA

description: Personal blog about amateur radio experiments and observations.

url: https://3z6ma.github.io

author:
  name: Adam 3Z6MA
  url: https://github.com/3Z6MA

theme: jekyll-theme-minimal

lang: en

timezone: Warsaw/Poland

repository: 3Z6MA/3Z6MA.github.io
