title: 3Z6MA Ham Radio Blog

description: Personal blog about amateur radio experiments and observations.

url: https://3z6ma.github.io

author:
  name: Adam 3Z6MA
  url: https://github.com/3Z6MA

theme: jekyll-theme-primer

lang: en

timezone: Warsaw/Poland
